# Generated by Django 4.0.4 on 2022-05-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_project', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
