# Generated by Django 4.0.4 on 2022-05-15 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_project', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('answer_likes', models.ManyToManyField(related_name='answer_likes', to=settings.AUTH_USER_MODEL, verbose_name='Answer likes')),
                ('answer_unlikes', models.ManyToManyField(related_name='answer_unlikes', to=settings.AUTH_USER_MODEL, verbose_name='Answer_unlikes')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_project.menu', verbose_name='Блюдо пользователя')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_project.reviews', verbose_name='Родитель')),
                ('review_likes', models.ManyToManyField(related_name='review_likes', to=settings.AUTH_USER_MODEL, verbose_name='Review Likes')),
                ('review_unlikes', models.ManyToManyField(related_name='review_unlikes', to=settings.AUTH_USER_MODEL, verbose_name='Review unlikes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь комментария')),
            ],
            options={
                'verbose_name': 'Комментарий пользователя',
                'verbose_name_plural': 'Комментарий пользователей',
            },
        ),
    ]
