# Generated by Django 4.0.4 on 2022-05-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_project', '0004_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='answer_likes',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='answer_unlikes',
        ),
    ]
