# Generated by Django 4.0.4 on 2022-05-17 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_project', '0005_remove_reviews_answer_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dish_likes',
            field=models.ManyToManyField(related_name='dish_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки блюдо'),
        ),
    ]
