# Generated by Django 4.0.4 on 2022-05-17 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_project', '0006_menu_dish_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('comment_likes', models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайк комментария')),
                ('comment_unlikes', models.ManyToManyField(related_name='comment_unlikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайк комментария')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь комментария')),
            ],
            options={
                'verbose_name': 'Комменатрий контактов',
                'verbose_name_plural': 'Комментарий контакту',
            },
        ),
    ]
