# Generated by Django 4.0.4 on 2022-05-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_project', '0007_contactreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactreview',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='contactreview',
            name='comment_unlikes',
        ),
    ]
