# Generated by Django 4.0.4 on 2022-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_project', '0008_remove_contactreview_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Комментарий о блюдо', 'verbose_name_plural': 'Комментарий о блюдов'},
        ),
        migrations.AddField(
            model_name='menu',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
